name: C Program Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install GCC and MinGW for Windows compilation
      run: |
        sudo apt update
        sudo apt-get install -y gcc

    - name: Run Makefile
      run: make

    - name: Upload compiled sherlock
      uses: actions/upload-artifact@v3
      with:
        name: sherlock
        path: sherlock